common: &common
  adapter: postgresql
  host: localhost
  username: postgres
  password: toor # from psql setup, see Postgresql

development:
  <<: *common
  database: twilater_dev

test:
  <<: *common
  database: twilater_test

production:
  <<: *common
  database: twilater